### PR TITLE
Test with Ruby 2.7, cache gems in CI

### PR DESCRIPTION
**Pull request by aried3r**

### CODE REVIEW

**Comment by aried3r** [comment]
Hmm, has Travis CI maybe been deactivated because of inactivity? @yolk, could you maybe take a look if you have time?

I'd like to add testing for Ruby 2.7 and Rails 6 :)

**Comment by yolk** [comment]
Hi @aried3r & thanks for the PR. The CI seems to work (see https://travis-ci.org/github/yolk/valvat/builds/681386826). Or is there something I am missing?

**Comment by aried3r** [comment]
Ah, I see. I was expecting Travis to use the GitHub API to report the check. Could you maybe look into that? It seems that it used to work, judging from old commits and PRs.

**Comment by yolk** [comment]
Ah okay... I just renewed the authorization for the CI in GH. Travis_CI now again has write access to the issues.

**Pull request merged**
