### PR TITLE
Fail if down with a specific message

### PR DESCRIPTION
**Pull request by pyromaniac**
Hello, first of all, thanks for a great gem.

I believe that we need a better message in cases when VIES is down to eliminate user's confusion. WDYT?

### CODE REVIEW

**Comment by pyromaniac** [comment]
The failed builds are unrelated to the PR. Do you think it is a time to drop ruby < 2.4 support? Cause it is EOL already.

**Comment by yolk** [comment]
First, thanks a lot for your contribution!

Maybe I don't get it, but what is the difference to the new (unreleased) feature of raising specific errors by default, documented at https://github.com/yolk/valvat#handling-of-vies-maintenance-errors ?

Maybe you could explain your intention in more detail.

**Comment by pyromaniac** [comment]
My idea is that the user gets a proper notification in the interface whenever VIES is down instead of this `VAT is invalid`, which is confusing because the VAT is potentially valid.

And handling exceptions requires an additional handling which can't be really done on the model/form level. So having a native validation message would work out of the box. And no one have to mess with a really specific exception handling.

**Comment by pyromaniac** [comment]
@yolk so what do you think about all this stuff?

**Comment by pyromaniac** [comment]
Hey, @yolk can I have some feedback on this very please?

**Comment by pyromaniac** [comment]
Also, do we need to support ruby before 2.4? It reached EOL already. Also, Rails 3 (and even maybe 4) might be dropped as well I believe. Can I do it here?

**Comment by yolk** [comment]
Salut @pyromaniac,

sorry for the late reply!

Regarding the support for ruby versions prior to 2.5 and activemodel before 5: I already planed to lower the support and just removed them from testing and the README. I guess I will push this out with 1.1

Regarding the original ticket: I now get your motivation. But maybe it would be better to not implement it as an option, but the new default behavior? I have a hard time imagining a case when it would be preferable to not tell the specific reason why the VAT can not be validated. This would mean to show the vies_down message by default if 'fail_if_down' is set to true. What do you think?

Another thing would be all the missing translation strings in locales/*.yml ... I could maybe add another 2 to 3 (badly) by myself. One possible solution could be to fall back to `messages.invalid_vat` if `messages.vies_down` is not available in the current locale?

**Comment by pyromaniac** [comment]
Ok, your proposal is awesome, going to implement it asap. Regarding the fallback: there is always a fallback to the default locale, let's maybe rely on it? Or just add the English translation to all the files? I think it is going to be less confusing for now.

**Comment by yolk** [comment]
Thanks for the quick response!

I think it would be better to leave the english version from the other locale files and depend on the fallback locale configured in rails.

**Comment by yolk** [comment]
Thanks a lot again!

**Comment by pyromaniac** [comment]
Thank for merging this! Any chance for it to be released as a new version any time soon?

**Comment by yolk** [comment]
I guess I'll release it next week. If you need the changes earlier you can always depend on it via git ref.

**Pull request merged**
